# Fórmula General de Transformación Afín en 2D

\[
$
\begin{bmatrix}
x' \\
y'
\end{bmatrix}$ = $\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}$
$\begin{bmatrix}
x \\
y
\end{bmatrix}$ + $\begin{bmatrix}
e \\
f
\end{bmatrix}$
\]


In [5]:
import numpy as np  # Importamos la biblioteca NumPy para trabajar con matrices y vectores

# Punto original (x, y)
punto_original = np.array([2, 3])  # Definimos el punto como un vector columna con coordenadas (2, 3)

# Matriz de transformación lineal (rotación, escala, sesgo)
matriz_lineal = np.array([[5, 6],  # Primer fila: afecta el eje x
                          [3, 2]]) # Segunda fila: afecta el eje y

# Vector de traslación (e, f)
traslacion = np.array([4, 6])  # Desplazamiento horizontal y vertical

# Paso 1: multiplicación matricial
producto = matriz_lineal @ punto_original  # Aplicamos la transformación lineal al punto
print("Paso 1 - Multiplicación de matriz lineal por punto:")
print(f"{matriz_lineal} @ {punto_original} = {producto}")  # Mostramos el resultado intermedio

# Paso 2: suma de traslación
punto_transformado = producto + traslacion  # Sumamos el vector de traslación al resultado anterior
print("\nPaso 2 - Suma del vector de traslación:")
print(f"{producto} + {traslacion} = {punto_transformado}")  # Mostramos el punto final transformado

Paso 1 - Multiplicación de matriz lineal por punto:
[[5 6]
 [3 2]] @ [2 3] = [28 12]

Paso 2 - Suma del vector de traslación:
[28 12] + [4 6] = [32 18]


# Forma Homogénea de la Transformación Afín en 2D

\[
$\begin{bmatrix}
x' \\
y' \\
1
\end{bmatrix}$ = $\begin{bmatrix}
a & b & e \\
c & d & f \\
0 & 0 & 1
\end{bmatrix}$ $\begin{bmatrix}
x \\
y \\
1
\end{bmatrix}$
\]

In [6]:
# Punto original en coordenadas homogéneas
punto_homogeneo = np.array([2, 3, 1])  # Agregamos el 1 para permitir la traslación como multiplicación

# Matriz afín homogénea
matriz_homogenea = np.array([[5, 6, 4],    # Primera fila: transformación + traslación en x
                             [3, 2, 6],   # Segunda fila: transformación + traslación en y
                             [0,   0,   1]])   # Tercera fila fija para mantener coordenadas homogéneas

# Paso único: multiplicación matricial
punto_transformado_h = matriz_homogenea @ punto_homogeneo  # Aplicamos la transformación completa
print("\nTransformación homogénea:")
print(f"{matriz_homogenea} @ {punto_homogeneo} = {punto_transformado_h}")  # Mostramos el resultado final


Transformación homogénea:
[[5 6 4]
 [3 2 6]
 [0 0 1]] @ [2 3 1] = [32 18  1]
